//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlikler
    {
        public int EtkinlikId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> UzmanGuidId { get; set; }
        public string EtkinlikAdi { get; set; }
        public string EtkinlikTipi { get; set; }
        public Nullable<System.DateTime> EtkinlikTarihSaati { get; set; }
        public Nullable<int> EtkinlikKatilimciSayisi { get; set; }
        public string EtkinlikDosyaYolu { get; set; }
    }
}
