//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciId { get; set; }
        public Nullable<System.Guid> KullaniciGuidId { get; set; }
        public string KullaniciTckn { get; set; }
        public string KullaniciAdiSoyadi { get; set; }
        public string KullaniciTipi { get; set; }
        public string KullaniciTelefonu { get; set; }
        public string KullaniciEpostasi { get; set; }
        public string KullaniciParolasi { get; set; }
        public string KullaniciCinsiyeti { get; set; }
        public string KullaniciMedeniHali { get; set; }
        public string KullaniciMeslegi { get; set; }
        public string KullaniciEgitimDuzeyi { get; set; }
        public string KullaniciOkuduguBolumu { get; set; }
        public string KullaniciSinifi { get; set; }
        public string KullaniciDanisanTipi { get; set; }
        public Nullable<System.DateTime> KullaniciDogumTarihi { get; set; }
        public string KullaniciIsGorevi { get; set; }
        public string KullaniciIsTelefonu { get; set; }
        public Nullable<int> KullaniciCocukSayisi { get; set; }
        public Nullable<bool> KullaniciPsikolojikDestek { get; set; }
        public Nullable<bool> KullaniciPsikolojikIlac { get; set; }
        public string DanisanYakinlikDerecesi { get; set; }
        public string DanisanYakiniAdiSoyadi { get; set; }
        public Nullable<int> DanisanYakiniYasi { get; set; }
        public string DanisanYakiniMeslegi { get; set; }
        public string DanisanYakiniTelefonu { get; set; }
        public string DanisanYakiniEgitimDuzeyi { get; set; }
        public string DanisanYakiniCalistigiBirim { get; set; }
        public string DanisanSorunAlani { get; set; }
        public string DanisanGelisNedeni { get; set; }
    }
}
