//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcekVeDanisan
    {
        public System.Guid OlcekGuidId { get; set; }
        public System.Guid DanisanGuidId { get; set; }
        public Nullable<System.DateTime> TarihSaat { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
