//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olcekler
    {
        public int OlcekId { get; set; }
        public Nullable<System.Guid> OlcekGuidId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string OlcekAdi { get; set; }
        public Nullable<int> OlcekSoruSayisi { get; set; }
        public Nullable<int> OlcekSecenekSayisi { get; set; }
        public Nullable<int> OlcekSecenekBasiPuani { get; set; }
        public string OlcekNot { get; set; }
    }
}
