//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcekSorular
    {
        public long OlcekSoruId { get; set; }
        public Nullable<System.Guid> OlcekGuidId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Soru { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> SoruNo { get; set; }
    }
}
