//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametreler
    {
        public int ParametreId { get; set; }
        public string ParametreDeger { get; set; }
        public string ParametreAdi { get; set; }
        public string ParametreGrup { get; set; }
        public Nullable<bool> ParametreAktifMi { get; set; }
    }
}
