//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPdrMerEntities : DbContext
    {
        public dbPdrMerEntities()
            : base("name=dbPdrMerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etkinlikler> Etkinlikler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<OlcekKullaniciSonuclar> OlcekKullaniciSonuclar { get; set; }
        public virtual DbSet<Olcekler> Olcekler { get; set; }
        public virtual DbSet<OlcekSecenekler> OlcekSecenekler { get; set; }
        public virtual DbSet<OlcekSorular> OlcekSorular { get; set; }
        public virtual DbSet<Parametreler> Parametreler { get; set; }
        public virtual DbSet<Randevular> Randevular { get; set; }
        public virtual DbSet<SabitTakvim> SabitTakvim { get; set; }
        public virtual DbSet<SistemLog> SistemLog { get; set; }
        public virtual DbSet<OlcekVeDanisan> OlcekVeDanisan { get; set; }
    }
}
