//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int RandevuId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> UzmanGuidId { get; set; }
        public Nullable<System.Guid> DanisanGuidId { get; set; }
        public Nullable<System.DateTime> RandevuTarihSaati { get; set; }
        public string RandevuOrtami { get; set; }
        public string RandevuDurumu { get; set; }
    }
}
