//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SabitTakvim
    {
        public long SabitTakvimID { get; set; }
        public string Gun { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public string SabitTakvimDurum { get; set; }
    }
}
