//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemLog
    {
        public long SistemLogId { get; set; }
        public string Metod { get; set; }
        public string LogDeger { get; set; }
        public string LogTipi { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string IP { get; set; }
    }
}
